export type ShopItemCategory =
  | 'weapon'
  | 'armor'
  | 'consumable'
  | 'gear'
  | 'wondrous'
  | 'scroll'
  | 'potion'
  | 'tool';

export interface ShopItem {
  id: string;
  name: string;
  category: ShopItemCategory;
  price: number; // Cost in GP
  currencyType: 'gp' | 'sp' | 'cp' | 'pp';
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Legendary';
  stock: number; // -1 for unlimited, or finite number
  weight: number; // lbs
  description: string;
  effect?: string;
  requiresAttunement?: boolean;
  visibleToPlayers: boolean;
  icon?: string;
}

export interface CampaignShop {
  id: string;
  name: string;
  shopkeeper: string;
  shopkeeperTitle: string;
  location: string;
  description: string;
  bannerColor: string;
  accentColor: string;
  icon: string;
  discountPercent: number; // e.g. 10 = 10% off, -20 = 20% markup
  isOpen: boolean;
  visibleToPlayers: boolean;
  items: ShopItem[];
}

export const DEFAULT_CAMPAIGN_SHOPS: CampaignShop[] = [
  {
    id: 'shop-apothecary',
    name: 'The Crimson Alembic',
    shopkeeper: 'Madam Evelyn Vane',
    shopkeeperTitle: 'Master Alchemist & Herbalist',
    location: 'Cobblestone Row, High Quarter',
    description: 'A cozy, dimly-lit apothecary reeking of dried hemlock, lavender, and bubbling copper distillers. Glass vials shimmer in velvet cases.',
    bannerColor: '#10b981',
    accentColor: '#34d399',
    icon: 'FlaskConical',
    discountPercent: 0,
    isOpen: true,
    visibleToPlayers: true,
    items: [
      {
        id: 'item-pot-heal',
        name: 'Potion of Healing',
        category: 'potion',
        price: 50,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 12,
        weight: 0.5,
        description: 'A glowing red liquid that sparkles when shaken.',
        effect: 'Regains 2d4 + 2 hit points as an action.',
        visibleToPlayers: true,
      },
      {
        id: 'item-pot-grheal',
        name: 'Potion of Greater Healing',
        category: 'potion',
        price: 150,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 6,
        weight: 0.5,
        description: 'A warm crimson draught with swirling golden dust.',
        effect: 'Regains 4d4 + 4 hit points as an action.',
        visibleToPlayers: true,
      },
      {
        id: 'item-pot-invis',
        name: 'Potion of Invisibility',
        category: 'potion',
        price: 800,
        currencyType: 'gp',
        rarity: 'Very Rare',
        stock: 1,
        weight: 0.5,
        description: 'An entirely clear glass phial that seems empty until tilted.',
        effect: 'Become invisible for 1 hour. Ends early if you attack or cast a spell.',
        visibleToPlayers: true,
      },
      {
        id: 'item-pot-giant',
        name: 'Elixir of Hill Giant Strength',
        category: 'potion',
        price: 400,
        currencyType: 'gp',
        rarity: 'Rare',
        stock: 2,
        weight: 0.5,
        description: 'A thick, pungent brew tasting of raw marrow and crushed stone.',
        effect: 'Your Strength score becomes 21 for 1 hour.',
        visibleToPlayers: true,
      },
      {
        id: 'item-antidote',
        name: 'Antitoxin Flask',
        category: 'consumable',
        price: 50,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 8,
        weight: 0.5,
        description: 'A bitter herbal tincture neutralizing venoms and toxics.',
        effect: 'Advantage on saving throws against poison for 1 hour.',
        visibleToPlayers: true,
      },
      {
        id: 'item-alch-fire',
        name: 'Alchemist’s Fire (Flask)',
        category: 'consumable',
        price: 50,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 5,
        weight: 1,
        description: 'Volatile orange oil that ignites on contact with air.',
        effect: 'Ranged attack (20 ft). On hit, target takes 1d4 fire damage at start of each turn until extinguished.',
        visibleToPlayers: true,
      },
    ],
  },
  {
    id: 'shop-blacksmith',
    name: 'Ironpeak Forge & Armory',
    shopkeeper: 'Brogun Ironshaper',
    shopkeeperTitle: 'Elder Armorsmith of the Clan',
    location: 'The Anvil District, Upper Ward',
    description: 'Massive blast furnaces roar day and night. Racks of masterwork steel, polished breastplates, and silvered blades line the soot-blackened stone walls.',
    bannerColor: '#f59e0b',
    accentColor: '#fbbf24',
    icon: 'Shield',
    discountPercent: 10, // 10% friendly clan discount!
    isOpen: true,
    visibleToPlayers: true,
    items: [
      {
        id: 'item-silv-longsword',
        name: 'Silvered Longsword',
        category: 'weapon',
        price: 115,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 3,
        weight: 3,
        description: 'A finely balanced longsword plated in refined alchemical silver.',
        effect: 'Overcomes non-magical damage immunities of lycanthropes, fiends, and undead. 1d8 (1d10 versatile) slashing.',
        visibleToPlayers: true,
      },
      {
        id: 'item-mithral-shirt',
        name: 'Mithral Chain Shirt',
        category: 'armor',
        price: 450,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 1,
        weight: 10,
        description: 'Incredibly light elven chain that makes no sound when worn under clothing.',
        effect: 'AC 13 + Dex modifier (max 2). No stealth disadvantage.',
        visibleToPlayers: true,
      },
      {
        id: 'item-adamant-plate',
        name: 'Adamantine Breastplate',
        category: 'armor',
        price: 600,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 1,
        weight: 20,
        description: 'Forged from ultra-dense meteoric black ore.',
        effect: 'AC 14 + Dex modifier (max 2). Any critical hit against you becomes a normal hit.',
        visibleToPlayers: true,
      },
      {
        id: 'item-shield-bashing',
        name: 'Reinforced Tower Shield',
        category: 'armor',
        price: 65,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 4,
        weight: 8,
        description: 'Heavy steel-rimmed oak shield bearing the emblem of the vigil.',
        effect: '+2 AC while wielded.',
        visibleToPlayers: true,
      },
      {
        id: 'item-plus1-dagger',
        name: 'Masterwork Stiletto +1',
        category: 'weapon',
        price: 350,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 2,
        weight: 1,
        description: 'Razor-edged dagger with hollow groove for delivering toxins.',
        effect: '+1 to attack and damage rolls. 1d4 + 1 piercing, Finesse, Light, Thrown (20/60).',
        visibleToPlayers: true,
      },
    ],
  },
  {
    id: 'shop-arcane',
    name: 'Arcane Vault of Netheril',
    shopkeeper: 'Arch-Curator Zephyros',
    shopkeeperTitle: 'Keeper of Ancient Ensorcellment',
    location: 'Spires of Starlight, Academic Quarter',
    description: 'Floating glass orbs cast prismatic constellations across shelves of enchanted talismans, crystalline wands, and ancient vellum scrolls.',
    bannerColor: '#8b5cf6',
    accentColor: '#a78bfa',
    icon: 'Sparkles',
    discountPercent: 0,
    isOpen: true,
    visibleToPlayers: true,
    items: [
      {
        id: 'item-bag-holding',
        name: 'Bag of Holding',
        category: 'wondrous',
        price: 450,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 2,
        weight: 15,
        description: 'Opens into an extradimensional space roughly 4 feet deep and 2 feet in diameter.',
        effect: 'Can hold up to 500 pounds while always weighing 15 lbs.',
        visibleToPlayers: true,
      },
      {
        id: 'item-ring-prot',
        name: 'Ring of Protection +1',
        category: 'wondrous',
        price: 1200,
        currencyType: 'gp',
        rarity: 'Rare',
        stock: 1,
        weight: 0.1,
        description: 'A platinum band set with a pulsing sapphire that projects a warding barrier.',
        effect: '+1 bonus to AC and saving throws while worn.',
        requiresAttunement: true,
        visibleToPlayers: true,
      },
      {
        id: 'item-wand-mm',
        name: 'Wand of Magic Missiles',
        category: 'wondrous',
        price: 400,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 1,
        weight: 1,
        description: 'Carved from petrified ash wood with a glowing quartz tip.',
        effect: 'Has 7 charges. Cast 1st-level Magic Missile (1 charge) or upcast for additional charges. Regains 1d6+1 daily.',
        visibleToPlayers: true,
      },
      {
        id: 'item-scroll-counter',
        name: 'Spell Scroll: Counterspell (3rd Level)',
        category: 'scroll',
        price: 300,
        currencyType: 'gp',
        rarity: 'Rare',
        stock: 2,
        weight: 0.1,
        description: 'A crisp parchment inscribed with abjuration sigils.',
        effect: 'Cast Counterspell as a reaction without expending a spell slot.',
        visibleToPlayers: true,
      },
      {
        id: 'item-pearl-power',
        name: 'Pearl of Power',
        category: 'wondrous',
        price: 550,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 1,
        weight: 0.1,
        description: 'A lustrous black pearl that hums with arcane resonance.',
        effect: 'Once per day, use an action to regain one expended spell slot of up to 3rd level.',
        requiresAttunement: true,
        visibleToPlayers: true,
      },
    ],
  },
  {
    id: 'shop-provisioner',
    name: 'The Wanderer’s Pack',
    shopkeeper: 'Old Tobbin & Granddaughter Pip',
    shopkeeperTitle: 'Town Outfitters & Guild Purveyors',
    location: 'Market Square, South Gate',
    description: 'Piles of canvas packs, coil after coil of hemp and silk rope, tallow torches, iron rations, and sturdy adventuring kits for surviving the wilds.',
    bannerColor: '#0ea5e9',
    accentColor: '#38bdf8',
    icon: 'Package',
    discountPercent: 0,
    isOpen: true,
    visibleToPlayers: true,
    items: [
      {
        id: 'item-thieves-tools',
        name: 'Thieves’ Tools',
        category: 'tool',
        price: 25,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 5,
        weight: 1,
        description: 'Set of picks, tension wrenches, small files, and mirrors.',
        effect: 'Add proficiency bonus to checks made to disarm traps or open locks.',
        visibleToPlayers: true,
      },
      {
        id: 'item-silk-rope',
        name: 'Silk Rope (50 ft.)',
        category: 'gear',
        price: 10,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 10,
        weight: 5,
        description: 'Strong, supple braided silk that holds up to 1,000 lbs.',
        visibleToPlayers: true,
      },
      {
        id: 'item-rations',
        name: 'Trail Rations (10 Days)',
        category: 'consumable',
        price: 5,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 20,
        weight: 10,
        description: 'Dried meats, hard biscuits, nuts, and preserved fruit.',
        visibleToPlayers: true,
      },
      {
        id: 'item-lantern',
        name: 'Bullseye Lantern',
        category: 'gear',
        price: 12,
        currencyType: 'gp',
        rarity: 'Common',
        stock: 4,
        weight: 2,
        description: 'Casts bright light in a 60-foot cone and dim light for an additional 60 feet for 6 hours per pint of oil.',
        visibleToPlayers: true,
      },
    ],
  },
  {
    id: 'shop-fence',
    name: 'The Gilded Rat (Secret Fence)',
    shopkeeper: 'Corvin "The Raven"',
    shopkeeperTitle: 'Underworld Broker & Fixer',
    location: 'Back Alley trapdoor beneath the Fishmonger stalls',
    description: 'Tucked behind false brickwork in the damp cellar beneath the docks. Forbidden poisons, smuggled lockpicks, counterfeit seals, and shadowy curios.',
    bannerColor: '#e11d48',
    accentColor: '#fb7185',
    icon: 'Skull',
    discountPercent: -15, // 15% black market markup!
    isOpen: true,
    visibleToPlayers: true,
    items: [
      {
        id: 'item-drow-poison',
        name: 'Drow Poison (Vial)',
        category: 'consumable',
        price: 200,
        currencyType: 'gp',
        rarity: 'Rare',
        stock: 2,
        weight: 0.1,
        description: 'Sticky dark oil distilled from Underdark fungi.',
        effect: 'Applied to weapon. DC 13 Con save or target falls Poisoned for 1 hour. If failed by 5 or more, target is Unconscious.',
        visibleToPlayers: true,
      },
      {
        id: 'item-smokepowder',
        name: 'Smokepowder Keg (10 lbs)',
        category: 'consumable',
        price: 250,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 1,
        weight: 10,
        description: 'Volatile explosive powder packed in a sealed iron cask.',
        effect: 'Ignites to deal 7d6 fire damage to everything in a 20-foot radius (DC 13 Dex save for half).',
        visibleToPlayers: true,
      },
      {
        id: 'item-false-papers',
        name: 'High Noble Forged Papers',
        category: 'gear',
        price: 125,
        currencyType: 'gp',
        rarity: 'Uncommon',
        stock: 2,
        weight: 0.1,
        description: 'Wax-sealed travel writ bearing the legitimate coat of arms of Duke Ravenscroft.',
        effect: 'Pass city checkpoints and private gates without suspicion.',
        visibleToPlayers: true,
      },
      {
        id: 'item-shadow-cloak',
        name: 'Cloak of the Shadow Guild',
        category: 'wondrous',
        price: 650,
        currencyType: 'gp',
        rarity: 'Rare',
        stock: 1,
        weight: 2,
        description: 'Deep obsidian cowl woven with shadow-silk that absorbs ambient light.',
        effect: 'Advantage on Stealth checks in dim light or darkness. Cast Darkness 1/day.',
        requiresAttunement: true,
        visibleToPlayers: true,
      },
    ],
  },
];
